# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MinRiskMaxReward
email: mnrskmxrwrd@minriskmaxreward.com
description: > # this means to ignore newlines until "baseurl:"
   Every actuarial study guide you'll ever need, in one place.
baseurl: minriskmaxreward.com
url: "http://minriskmaxreward.com" # the base hostname & protocol for your site
twitter_username: mnrskmxrwrd
github_username:  pag22

# Build settings
markdown: kramdown
